### ISSUE TITLE
Accept general terms + gdpr should be 1 button only

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/actionwidget#5]
It should link to external URL with agreement and all GDPR stuff. Please provide us a text (that we can show in popover) or a link to an external website to show this.

**Comment by samtaggart** [comment]
Confirmed we need three, will get you the proper text ASAP.

**Comment by samtaggart** [comment]
We need the following:

- [ ] I hereby accept this site's privacy policy [link to the policy].
- [ ] I accept this site's Cookie Policy [link to the policy]. (We use third party analytics cookies to provide us with information on the usage of our website and in order to optimize and improve our website. You can customize your cookie consent at any time using your browser settings.)
- [ ] I hereby agree to the processing and use of my email address by TF Tech NV in view of sending me occasional commercial communications.

**Comment by samtaggart** [comment]
I know this is quite long but let's go with it for now and may need to change later. Waiting on feedback from Pierre (legal counsel).

**Comment by KristofVanstappen** [comment]
@samtaggart can you give me the links to the policies?

**Comment by samtaggart** [comment]
This is where we are:

https://docs.google.com/document/d/16i6M2Bkxh0o5kbDOuBCnErPJ_OKM1uLkgPWJwexZ9lQ/edit#

This is the privacy policy, which includes the cookie policy within.

Can you upload it on a blank white page or should I get someone else to do it?

**Comment by jdelrue** [comment]
@despiegk Can you review if you agree with this?

**Comment by Sacha96** [comment]
everything is now privacy policy. details already linked. We need to host it on a private web page (not google etc..)
